export {default as Home } from './Home'
export {default as Login } from './Login'
export {default as Signup } from './Signup'
export {default as Splash } from './Splash'
export {default as AddToChat } from './AddToChat'
export {default as Chat } from './Chat'
